core/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import custom_login
from dashboard.views import (
    people_counter,
    users_list,
    generate_user,
    user_permissions,
    home,
    profile,
    branch_permissions,
    campaign,
    create_campaign,
    edit_campaign,
    delete_campaign,
    upload_excel_file_invoice,
    invoices,
    invoice_detail,
    invoice_delete,
    excel_template_generator,
    invoice_counter,
    analysis,
    campaign_detail,
    campaign_comparison,
    holiday_spotter,
    camera_list,
    alert_menu,
    alert_form_sms,
    alert_from_sms_contact_list,
    alert_from_sms_contact_list_detail,
    alert_form_social,
    alert_form_sms_edit,
    grouped_campaign_search_as_type,
    single_campaign_search_as_type,
    people_counting_hourly,
    website_stats
)
from dashboard.api_views import (
    MultipleBranches,
    MultiBranchesInvoice,
    Analysis,
    GetCampaignEachPoint,
    GroupedCampaigns,
    GroupedCampaignComparison,
    CampaignComparison,
    HolidaySpotter,
    CamStatus,
    NormalWeeklyDisplay,
    NormalMonthlyDisplay,
    abNormalWeeklyDisplay,
    abNormalMonthlyDisplay,
    AI,
    AIWebsite,
    MultipleBranchesHourly
)
from django.contrib.auth import views as auth_views
from django.contrib import admin

admin.site.site_header = "پنل مدیریت اسپات لاین"
admin.site.site_title = "پنل مدیریت اسپات لاین"
admin.site.index_title = "پنل مدیریت اسپات لاین"


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "dashboard/people-counter/<str:url_hash>", people_counter, name="people_counter"
    ),
    path(
        "dashboard/people-counter-hourly/<str:url_hash>", people_counting_hourly, name="people_counting_hourly"
    ),
    path(
        "dashboard/website-stats/<str:url_hash>", website_stats, name="website_stats"
    ),
    path("dashboard/users/<str:url_hash>", users_list, name="users"),
    path("dashboard/generate-user/<str:url_hash>", generate_user, name="generate_user"),
    path(
        "dashboard/edit-user-permissions/<int:user_id>/",
        user_permissions,
        name="edit-user-permissions",
    ),
    path(
        "dashboard/edit-branch-permissions/<int:user_id>/",
        branch_permissions,
        name="edit-branch-permissions",
    ),
    path("dashboard/campaigns/<str:url_hash>", campaign, name="campaign"),
    path("dashboard/campaign-comparison/<str:url_hash>", campaign_comparison, name="campaign_comparison"),
    path(
        "dashboard/create-campaign/<str:url_hash>",
        create_campaign,
        name="create_campaign",
    ),
    path(
        "dashboard/edit-campaign/<str:url_hash>/<uuid:group_id>",
        edit_campaign,
        name="edit_campaign",
    ),
    path(
        "dashboard/delete-campaign/<str:url_hash>/<uuid:group_id>",
        delete_campaign,
        name="delete_campaign",
    ),
    path(
        "dashboard/campaign-solo-analysis/<int:campaign_id>",
        campaign_detail,
        name="campaign_solo_analysis",
    ),
    path(
        "dashboard/create-invoice-from-excel/<str:url_hash>",
        upload_excel_file_invoice,
        name="upload_excel_file_invoice",
    ),
    path("dashboard/invoices/<str:url_hash>", invoices, name="invoices"),
    path(
        "dashboard/invoices/invoice-detail/<int:invoice_pk>",
        invoice_detail,
        name="invoice_detail",
    ),
    path(
        "dashboard/invoice-delete/<int:invoice_pk>",
        invoice_delete,
        name="invoice_delete",
    ),
    path(
        "dashboard/excel-template-generator/<str:url_hash>",
        excel_template_generator,
        name="excel_template_generator",
    ),
    path(
        "dashboard/sales-counter/<str:url_hash>",
        invoice_counter,
        name="invoice_counter",
    ),
    path("dashboard/analysis/<str:url_hash>", analysis, name="analysis"),
    path("dashboard/account/login", custom_login, name="login"),
    path(
        "dashboard/account/logout/",
        auth_views.LogoutView.as_view(next_page="login"),
        name="logout",
    ),
    path("dashboard/account/profile/<int:user_id>/", profile, name="profile"),
    path("dashboard/<str:url_hash>", home, name="home"),
    path("api/multi-branch-data", MultipleBranches.as_view(), name="multi_branch_data"),
    path("api/multi-branch-data-hourly", MultipleBranchesHourly.as_view(), name="multi_branch_data_hourly"),
    path(
        "api/multi-branch-invoice-data",
        MultiBranchesInvoice.as_view(),
        name="multi_branch_invoice_data",
    ),
    path("api/analysis", Analysis.as_view(), name="analysis"),
    path(
        "api/get-campaign-each-point",
        GetCampaignEachPoint.as_view(),
        name="get_campaign_each_point",
    ),
    path("api/grouped-campaigns", GroupedCampaigns.as_view(), name="grouped_campaigns"),
    path("api/grouped-campaigns-comparison", GroupedCampaignComparison.as_view(), name="grouped_campaigns_comparison"),
    path("api/single-campaigns-comparison", CampaignComparison.as_view(), name="campaigns_comparison"),
    path("dashboard/camera-list/<str:url_hash>", camera_list, name="camera_list"), 
    path("api/holiday-spotter/<str:year>/<str:month>/<str:day>/", holiday_spotter, name="holiday_spotter"),
    path("api/holiday-spot", HolidaySpotter.as_view(), name="holiday_spot"),
    path("api/cam-status", CamStatus.as_view(), name="cam_status"),
    path("api/normal-weekly-display", NormalWeeklyDisplay.as_view(), name="normal-weekly-display"),
    path("api/normal-monthly-display", NormalMonthlyDisplay.as_view(), name="normal-monthly-display"),
    path("api/abnormal-weekly-display", abNormalWeeklyDisplay.as_view(), name="abnormal-weekly-display"),
    path("api/abnormal-monthly-display", abNormalMonthlyDisplay.as_view(), name="abnormal-monthly-display"),
    path("api/ai", AI.as_view(), name='ai'),
    path("api/ai-website", AIWebsite.as_view(), name='ai-website'),
    path("dashboard/alert-menu/<str:url_hash>", alert_menu, name="alert_menu"),
    path("dashboard/alert-form-sms/<str:url_hash>", alert_form_sms, name="alert_form_sms"),
    path("dahsboard/alert-form-social/<str:url_hash>", alert_form_social, name="alert_form_social"),
    path("dashboard/alert-from-sms-contact-list/<str:url_hash>", alert_from_sms_contact_list, name="alert-from-sms-contact-list"),
    path("dashboard/alert-from-sms-contact-list-detail/<int:contact_id>", alert_from_sms_contact_list_detail, name="alert-from-sms-contact-list-detail"),
    path("dashboard/alert-form-sms-edit/<int:contact_id>", alert_form_sms_edit, name="alert-form-sms-edit"),
    path("dashboard/search/grouped-campaign-search-as-type/", grouped_campaign_search_as_type, name="grouped_campaign_search_as_type"),
    path("dashboard/search/single-campaign-search-as-type/", single_campaign_search_as_type, name="single_campaign_search_as_type"),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Merchant(models.Model):
    name = models.CharField(max_length=255, verbose_name="نام")
    rep_first_name = models.CharField(max_length=255, verbose_name="نام نماینده")
    rep_last_name = models.CharField(
        max_length=255, verbose_name="نام خانوادگی نماینده"
    )
    rep_mobile_number = models.CharField(
        max_length=11, verbose_name="شماره موبایل نماینده"
    )
    contract_start_date = models.DateField(verbose_name="تاریخ شروع قرارداد")
    contract_expiration_date = models.DateField(verbose_name="تاریخ انقضای قرارداد")
    url_hash = models.CharField(
        max_length=25, verbose_name="نامک", null=True, db_index=True, unique=True
    )  # remove null True in Production
    date_created = models.DateTimeField(
        null=True, default=datetime.now, verbose_name="تاریخ ساخت"
    )
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name="تاریخ آخرین تغییر"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "مرچنت"
        verbose_name_plural = "مرچنت"


class Country(models.Model):
    name = models.CharField(max_length=255, verbose_name="نام")
    date_created = models.DateTimeField(
        null=True, default=datetime.now, verbose_name="تاریخ ساخت"
    )
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name="تاریخ آخرین تغییر"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "کشور"
        verbose_name_plural = "کشور"


class Province(models.Model):
    name = models.CharField(max_length=255, verbose_name="نام")
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name="کشور")
    date_created = models.DateTimeField(
        null=True, default=datetime.now, verbose_name="تاریخ ساخت"
    )
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name="تاریخ آخرین تغییر"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "استان"
        verbose_name_plural = "استان"


class City(models.Model):
    name = models.CharField(max_length=255, verbose_name="نام")
    province = models.ForeignKey(
        Province, on_delete=models.CASCADE, verbose_name="استان"
    )
    date_created = models.DateTimeField(
        null=True, default=datetime.now, verbose_name="تاریخ ساخت"
    )
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name="تاریخ آخرین تغییر"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "شهر"
        verbose_name_plural = "شهر"


class District(models.Model):
    name = models.CharField(max_length=255, verbose_name="نام")
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="شهر")
    date_created = models.DateTimeField(
        null=True, default=datetime.now, verbose_name="تاریخ ساخت"
    )
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name="تاریخ آخرین تغییر"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "منطقه"
        verbose_name_plural = "منطقه"


class Branch(models.Model):
    merchant = models.ForeignKey(
        Merchant, on_delete=models.CASCADE, verbose_name="مرچنت", db_index=True
    )
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE, verbose_name="کشور", null=True, blank=True
    )
    province = models.ForeignKey(
        Province, on_delete=models.CASCADE, verbose_name="استان", null=True, blank=True
    )
    city = models.ForeignKey(
        City, on_delete=models.CASCADE, verbose_name="شهر", null=True, blank=True
    )
    district = models.ForeignKey(
        District, on_delete=models.CASCADE, verbose_name="منطقه", null=True, blank=True
    )
    name = models.CharField(max_length=255, verbose_name="نام", db_index=True, unique=True)
    date_created = models.DateTimeField(
        null=True, default=datetime.now, verbose_name="تاریخ ساخت"
    )
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name="تاریخ آخرین تغییر"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "شعبه"
        verbose_name_plural = "شعبه"


class Cam(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name="کشور")
    province = models.ForeignKey(
        Province, on_delete=models.CASCADE, verbose_name="استان"
    )
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="شهر")
    district = models.ForeignKey(
        District, on_delete=models.CASCADE, verbose_name="منطقه"
    )
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, verbose_name="شعبه")
    zone = models.CharField(max_length=255, verbose_name="زون")
    entry = models.CharField(max_length=255, verbose_name="ورودی")
    ip = models.CharField(max_length=255, verbose_name="IP")
    cam_name = models.CharField(max_length=255, verbose_name="نام")
    merchant = models.ForeignKey(
        Merchant, on_delete=models.CASCADE, verbose_name="مرچنت"
    )
    google_longitude = models.CharField(max_length=255, verbose_name="Google Latitude")
    google_latitude = models.CharField(max_length=255, verbose_name="Google Longitude")
    date_created = models.DateTimeField(
        null=True, default=datetime.now, verbose_name="تاریخ ساخت"
    )
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name="تاریخ آخرین تغییر"
    )
    status = models.BooleanField(null=True, verbose_name="وضعیت", blank=True)

    def __str__(self):
        return f"{self.cam_name} {self.ip}"

    class Meta:
        verbose_name = "دوربین"
        verbose_name_plural = "دوربین"


class PeopleCounting(models.Model):
    date = models.DateField(verbose_name="تاریخ", db_index=True)
    entry = models.IntegerField(default=0, verbose_name="ورودی")
    exit = models.IntegerField(default=0, verbose_name="خروجی")
    cam = models.ForeignKey(
        Cam,
        on_delete=models.CASCADE,
        verbose_name="دوربین",
        related_name="people_counts",
    )
    merchant = models.ForeignKey(
        Merchant,
        on_delete=models.CASCADE,
        verbose_name="مرچنت",
        related_name="people_counts",
        db_index=True,
    )
    branch = models.ForeignKey(
        Branch,
        on_delete=models.CASCADE,
        verbose_name="شعبه",
        related_name="people_counts",
        db_index=True,
    )
    date_created = models.DateTimeField(
        null=True, default=datetime.now, verbose_name="تاریخ ساخت"
    )
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name="تاریخ آخرین تغییر"
    )

    def __str__(self):
        return f"{self.merchant.name} {self.branch.name} {self.cam.ip}"

    class Meta:
        verbose_name = "شمارشگر"
        verbose_name_plural = "شمارشگر"
        indexes = [models.Index(fields=["merchant", "date"])]


class Campaign(models.Model):
    campaign_types = [("ویترین", "ویترین"), ("فروش", "فروش")]
    group_id = models.CharField(max_length=36, null=True, blank=True, db_index=True)
    name = models.CharField(max_length=255, verbose_name="نام کمپین")
    start_date = models.DateField(verbose_name="تاریخ", db_index=True)
    end_date = models.DateField(
        verbose_name="تاریخ پایان", null=True, blank=True, db_index=True
    )
    campaign_type = models.CharField(
        choices=campaign_types,
        null=True,
        blank=True,
        max_length=10,
        verbose_name="نوع کمپین",
    )
    branch = models.ForeignKey(
        Branch, on_delete=models.CASCADE, verbose_name="شعبه", db_index=True
    )
    cost = models.CharField(max_length=255, verbose_name="هزینه", null=True, blank=True)
    date_created = models.DateTimeField(
        null=True, default=datetime.now, verbose_name="تاریخ ساخت"
    )
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name="تاریخ آخرین تغییر"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "کمپین"
        verbose_name_plural = "کمپین"
        indexes = [models.Index(fields=["branch", "start_date", "end_date"])]


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile",
        verbose_name="کاربر",
        db_index=True,
    )
    merchant = models.ForeignKey(
        Merchant,
        on_delete=models.CASCADE,
        related_name="profile",
        verbose_name="مرچنت",
        db_index=True,
    )
    mobile = models.CharField(
        max_length=11, verbose_name="شماره تلفن", null=True, blank=True
    )
    is_manager = models.BooleanField(default=False, verbose_name="مدیر", db_index=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

    class Meta:
        verbose_name = "نمای کاربر"
        verbose_name_plural = "نمای کاربر"


class PermissionToViewBranch(models.Model):
    user = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE,
        related_name="permissiontoviewbranch",
        verbose_name="کاربر",
        db_index=True,
    )
    branch = models.ForeignKey(
        Branch,
        on_delete=models.CASCADE,
        related_name="permissiontoviewbranch",
        verbose_name="شعبه",
        db_index=True,
    )
    date_created = models.DateTimeField(
        null=True, default=datetime.now, verbose_name="تاریخ ساخت"
    )
    last_modified = models.DateTimeField(
        auto_now=True, verbose_name="تاریخ آخرین تغییر"
    )

    def __str__(self):
        return f"{self.pk}"

    class Meta:
        verbose_name = "مجوز شعبه"
        verbose_name_plural = "مجوز شعبه"


class Invoice(models.Model):
    date = models.DateField(verbose_name="تاریخ", db_index=True)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, db_index=True)

dashboard/templates/alert-form-social.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	فرم اطلاع رسانی گزارش روزانه 
{% endblock %}
{% block meta_description %}
	 فرم اطلاع رسانی گزارش روزانه
{% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
    {% if request.user.is_superuser %}
    <h4 class="py-3 breadcrumb-wrapper mb-4">فرم اطلاع رسانی گزارش روزانه</h4>
    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
              <div class="card mb-4">
                <div class="card-body">
                  <div>
                    <label for="id_first_name" class="form-label">نام</label>
                    <input type="text" class="form-control" name="first_name" id="id_first_name" aria-describedby="defaultFormControlHelp">
                    <label for="id_last_name" class="form-label">شماره موبایل</label>
                    <input type="text" class="form-control" name="last_name" id="id_last_name" aria-describedby="defaultFormControlHelp">
                    <label for="id_username" class="form-label">آی دی تلگرام</label>
                    <input type="text" class="form-control" name="username" id="id_username" aria-describedby="defaultFormControlHelp">
                    <div id="options">
                    <label class="form-label" style="margin-top: 20px;">گزارش مورد نظر را انتخاب کنید</label>
                        <div>
                            <label class="form-check-label"><input class="form-check-input" type="checkbox" name="branch" value="1" aria-invalid="true" style="margin-left: 10px;">گزارش ترافیک روزانه</label>
                        </div>
                        <div>
                            <label class="form-check-label"><input class="form-check-input" type="checkbox" name="branch" value="2" aria-invalid="true" style="margin-left: 10px;">گزارش تعداد فلکتور روزانه</label>
                        </div>
                        <div>
                            <label class="form-check-label"><input class="form-check-input" type="checkbox" name="branch" value="3" aria-invalid="true" style="margin-left: 10px;">گزارش ریالی فروش روزانه</label>
                        </div>
                        <div>
                            <label class="form-check-label"><input class="form-check-input" type="checkbox" name="branch" value="4" aria-invalid="true" style="margin-left: 10px;">گزارش نرخ تبدیل روزانه</label>
                        </div>
                    </div>
                    <div class="form-check form-switch mb-2" style="margin-top: 20px;">
                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" name="is_staff">
                        <label class="form-check-label" for="id_is_staff">ارسال گزارش در تلگرام</label>
                    </div>
                    <div class="form-check form-switch mb-2" style="margin-top: 20px;">
                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" name="is_active">
                        <label class="form-check-label" for="id_is_active">ارسال گزارش در واتساپ</label>
                    </div>
                    <label for="flatpickr-time" class="form-label" style="margin-top: 20px;">انتخاب‌گر زمان</label>
                    <input type="text" id="flatpickr-time" class="form-control" placeholder="HH:MM">
                    <button class="btn btn-primary" type="submit" style="margin-top: 20px;">ثبت</button>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </form>
{% else %}
<p>شما اجازه دسترسی به این قسمت را ندارید</p>
{% endif %}
{% endif %}
{% endblock %}
{% block extra_js %}
<!-- Flatpickr JS -->
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
  flatpickr("#flatpickr-time", {
    enableTime: true,
    noCalendar: true,
    dateFormat: "H:i",
    time_24hr: true
  });
</script>
{% endblock %}

dashboard/templates/alert_form_sms_edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	ویرایش مخاطب دریافت پیامک
{% endblock %}
{% block meta_description %}
	ویرایش مخاطب دریافت پیامک
{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
    {% if request.user.is_superuser %}
    <div class="d-flex align-items-center py-3 mb-4">
        <i class='bx bx-user-pin bx-lg text-primary me-3'></i>
        <div>
            <h4 class="mb-1">ویرایش مخاطب دریافت پیامک</h4>
            <p class="text-muted mb-0">اطلاعات مخاطب را در این قسمت ویرایش کنید</p>
        </div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
              <div class="card mb-4">
                <div class="card-body">
                  <div>
                    <i class='bx bx-user text-muted'></i>
                    <label class="form-label" for="id_name">نام:</label>
                    <input type="text" class="form-control" name="name" value="{{contact.name}}" maxlength="255" required="" id="id_name">
                    <i class='bx bx-mobile-alt text-muted'></i>
                    <label class="form-label" for="id_mobile" style="margin-top: 20px;">شماره موبایل:</label>
                    <input type="number" class="form-control" name="mobile" value="{{contact.mobile}}" maxlength="11" required="" id="id_mobile" pattern="09[0-9]{9}" placeholder="09xxxxxxxxx">
                    <div class="form-check form-switch" style="margin-top: 20px;">
                      <label class="form-check-label" for="flexSwitchCheckDefault">فعال</label>
                      <input class="form-check-input" type="checkbox" name="is_active" id="flexSwitchCheckDefault" checked="">
                      <p style="display: none;" id="check-checkbox">{{contact.is_active}}</p>
                    </div>
                    <small class="form-text">در صورت فعال بودن، مخاطب پیامک دریافت می‌کند</small>
                  </div>
                </div>
                <div style="display: flex; justify-content: center; align-items: center; flex-direction: row;">
                    <button class="btn btn-primary" type="submit" style="margin: 20px; width: 40%;"><i style="margin-left: 10px;" class='bx bx-save me-2'></i> ثبت</button>
                    <a onclick="window.history.back()" class="btn btn-secondary" type="button" style="margin: 20px; width: 40%; color: white;"><i style="margin-left: 10px;" class='bx bx-arrow-back me-2'></i> بازگشت</a>
                </div>
              </div>
            </div>
        </div>
    </form>
    {% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
          <div style="display: none;" class="alert alert-success" role="alert">{{ message }}</div>
          {% elif message.tags == 'warning' %}
          <div style="display: none;" class="alert alert-warning" role="alert">{{ message }}</div>
          {% else %}
          <div style="display: none;" class="alert alert-danger" role="alert">{{ message }}</div>
        {% endif %}
    {% endfor %}
{% endif %}
{% else %}
<p>شما اجازه دسترسی به این قسمت را ندارید</p>
{% endif %}
{% endif %}
{% endblock %}
{% block extra_js %}
<!-- Sweet Alert CDN -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<!--Check Checkbox-->
<script>
    const checkCheckbox = document.getElementById("check-checkbox");
    const thisCheckbox = document.querySelector(".form-check-input");
    if (checkCheckbox.innerText === "True") {
        thisCheckbox.checked = true;
    } else {
        thisCheckbox.checked = false;
    }
</script>
<!-- Pop Ups -->
<script>
  try {
    const successContainer = document.querySelector(".alert-success");
    if (successContainer) {
      const success = successContainer.innerText;
        Swal.fire({
        icon: "success",
        title: "موفق",
        html: `${success}<br><br><a class="btn btn-primary" href="{% url 'alert-from-sms-contact-list' url_hash=request.user.profile.merchant.url_hash|default:'defaulthash' %}">بستن</a>`,
        showConfirmButton: false,
      });
    }
  } catch (error) {
    console.log(error);
  }
  
  try {
    const errorContainer = document.querySelector(".alert-danger");
    if (errorContainer.children.length >= 1) {
      const error = document.querySelector(".errorlist li .errorlist li").innerText;
        Swal.fire({
        icon: "error",
        title: "خطا",
        html: `${error}`,
        confirmButtonColor: '#5a8dee',
        confirmButtonText: 'بستن' 
      });
    }
  } catch (error) {
    console.log(error);
  }
</script>
{% endblock %}

dashboard/templates/delete-campaign.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    حذف کمپین
{% endblock %}
{% block meta_description %}
	حذف کمپین
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12 col-lg-7 mb-4 order-2 order-lg-0">
        <div class="card h-100" style="
        background-clip: padding-box;
        border-style: solid;
        box-shadow: none;
        border-width: 1px;
        border-color: #e5e5e5;
        border-radius: 12px;
        padding: 10px;
            ">
        <div class="card-header d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center me-3">
            <div class="card-title mb-0">
                <h5 class="mb-0">{{ campaign.campaign_name }}</h5>
                <small class="text-muted primary-font">آیا مایلید کمپین زیر را حذف نمایید؟</small>
            </div>
            </div>
        </div>
        <div class="card-body">
            <div class="d-flex flex-wrap gap-4 mb-5 mt-4">
            <div class="d-flex flex-column me-2">
                <h6>تاریخ شروع</h6>
                <span class="badge bg-label-success">{{ jalali_start_date }}</span>
            </div>
            <div class="d-flex flex-column me-2">
                <h6>تاریخ پایان</h6>
                <span class="badge bg-label-danger">{{ jalali_end_date }}</span>
            </div>
            <div class="d-flex flex-column me-2">
                <h6>هزینه کمپین</h6>
                <span class="price">{{ campaign.campaign_cost|floatformat:0 }}</span>
            </div>
            <div class="d-flex flex-column me-2">
                <h6>نوع کمپین</h6>
                <span>{{ campaign.campaign_type }}</span>
            </div>
            <div class="d-flex flex-column me-2">
                <h6>شعبه</h6>
                <span>{{ campaign.branch_names }}</span>
            </div>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">حذف</button>
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extra_js %}
<script src="{% static 'assets/js/price-separator.js' %}"></script>
{% endblock %}